### PR TITLE
Use graceful-fs to avoid EMFILE error (too many open files.)

### PR DESCRIPTION
**Pull request by btimby**
Pretty simple change, I received this error when trying to queue 100000 messages. With this change, they are all queued and processed.

### CODE REVIEW

**Comment by threez** [comment]
Thx for your PR. I have a few questions before:

- Why don't you just use `global-fs` function "Global Patching"?
- If you receive EMFILE, did you try increasing the number of open files on your system? What was the result?

**Comment by btimby** [comment]
1. Let me address your first question with two points.

 - I see this as a defect in the queue. A common use case for a queue system is to handle load spikes. Anything other than a toy using file-queue will fall down under a load spike.

 - Global patching should not be done from within a library. So it would require a user to take action to fix a defect in the library. Not to mention there may be side-effects to global patching if the application uses `fs` in other capacities.

2. Increasing fd limit does "solve" the problem. But running production systems for as long as I have has taught me that this is not a real solution. As your usage grows (which is your goal in any software project) the problem will just continue to recur. Further, resource limits are in place for a reason, if my queue consumes all or nearly all of the allowed fds, then that likely impacts other processes. Well behaved software can be configured to respect your limits and work within those confines.

The above said, I think the problem is something common enough to warrant resolution within the library itself rather than being left to the user to bump into. Further, graceful-fs does allow the queue size to be adjusted, exposing that to the user via an option might be beneficial, so that the user can tune the value relative to the fd limit they impose.

**Comment by threez** [comment]
I see your problem, but I don't like depending on `global-fs`. It there are some errors that `global-fs` handles more nicely than the regular `fs` I really like to support you using it. I still think, that the library and it's users need to deal with the error cases that can occur.

What do you think about this:

```
var Queue = require('file-queue').Queue,
    queue = new Queue('.', { "fs": require('graceful-fs') }, callback);
```

I would then also update the documentation, so that people are aware of it.

**Comment by btimby** [comment]
I think that is a good solution.

**Pull request closed without merging**
